name: translate_finder
description: A sample command-line application to extract translate text inside a nuxt project.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  path: ^1.8.0
  args:
  dart_clipboard: ^0.3.0
  bloc: ^8.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
